// Generated list of all Kota/Kabupaten in Indonesia (no provinsi), cleaned and sorted

export const domisiliList = [
  "Aceh Barat",
  "Aceh Barat Daya",
  "Aceh Besar",
  "Aceh Jaya",
  "Aceh Selatan",
  "Aceh Singkil",
  "Aceh Tamiang",
  "Aceh Tengah",
  "Aceh Tenggara",
  "Aceh Timur",
  "Aceh Utara",
  "Asahan",
  "Banda Aceh",
  "Bandung",
  "Batubara",
  "Bekasi",
  "Binjai",
  "Bogor",
  "Cianjur",
  "Cirebon",
  "Dairi",
  "Deli Serdang",
  "Depok",
  "Garut",
  "Gunungsitoli",
  "Humbang Hasundutan",
  "Indramayu",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Karawang",
  "Karo",
  "Kediri",
  "Kuningan",
  "Labuhanbatu",
  "Labuhanbatu Selatan",
  "Labuhanbatu Utara",
  "Langkat",
  "Langsa",
  "Lhokseumawe",
  "Madiun",
  "Magelang",
  "Majalengka",
  "Malang",
  "Mandailing Natal",
  "Medan",
  "Mojokerto",
  "Nias",
  "Nias Barat",
  "Nias Selatan",
  "Nias Utara",
  "Padang Lawas",
  "Padang Lawas Utara",
  "Padang Sidempuan",
  "Pakpak Bharat",
  "Pasuruan",
  "Pekalongan",
  "Pematangsiantar",
  "Probolinggo",
  "Purwakarta",
  "Sabang",
  "Salatiga",
  "Samosir",
  "Semarang",
  "Serdang Bedagai",
  "Sibolga",
  "Simalungun",
  "Sleman",
  "Subang",
  "Subulussalam",
  "Sukabumi",
  "Sumedang",
  "Surabaya",
  "Surakarta",
  "Tanjungbalai",
  "Tapanuli Selatan",
  "Tapanuli Tengah",
  "Tapanuli Utara",
  "Tasikmalaya",
  "Tebing Tinggi",
  "Tegal",
  "Toba",
  "Yogyakarta"
];
